name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # for each workflow & branch/PR/tag
  cancel-in-progress: true

jobs:
  build:
    name: Lint & build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v6
      - name: Detect if any Caddyfile was changed
        id: caddyfile-changed
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
        with:
          files: |
            example.Caddyfile
      - name: Install Caddy for linting
        if: steps.caddyfile-changed.outputs.any_changed == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y caddy
      - name: Enable Corepack for PNPM
        run: corepack enable
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Lint & Type-check
        run: pnpm run checkAll
      - name: Check Caddyfile style
        if: steps.caddyfile-changed.outputs.any_changed == 'true'
        run: |
          # Caddy in Ubuntu 24.04 is version 2.6.2, which lacks support for "-d"
          caddy fmt --diff example.Caddyfile
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
      - name: Run build
        run: pnpm run build
      - name: Upload pages artifacts
        uses: actions/upload-artifact@v6
        with:
          path: "./.vitepress/dist/"
          name: "pages-${{ github.sha }}"

  deploy-cf-pages:
    name: Deploy to Cloudflare Pages
    # only run for PRs
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      deployments: write
    environment:
      name: preview
    steps:
      - name: Check out the source code
        uses: actions/checkout@v6

      # Needed by wrangler-action for acquiring wrangler itself
      - name: Enable Corepack for PNPM
        run: corepack enable
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Download pages artifacts
        uses: actions/download-artifact@v6
        with:
          name: "pages-${{ github.sha }}"
          path: ".vitepress/dist"
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vitepress/dist --project-name=loongfans
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
